version: '3.5'
services:
  db:
    image: 'mysql:8'
    container_name: 'db'
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "sia"
      MYSQL_ROOT_PASSWORD: "Ge@140019"
    networks:
      - app-network
  web:
    container_name: web
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge